services:
  pg-ext:
    build:
      context: .
      dockerfile: dockerfile-pg-ext
    container_name: nest-base-pg-ext
    environment:
      POSTGRES_USER: nest-base
      POSTGRES_PASSWORD: nest-base
      POSTGRES_DB: postgres
    ports:
      - 1004:5432
    command: >
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=postgres
      -c cron.log_run=off
    # disable logging of all cron job runs
    # -c cron.log_run=off
